# Generated by Django 4.2.3 on 2023-07-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wins',
            field=models.IntegerField(),
        ),
    ]
