# Generated by Django 4.2.3 on 2023-07-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='winrate',
            field=models.FloatField(default=0),
        ),
    ]
