# Generated by Django 4.2.3 on 2023-07-17 16:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmaking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='matchmaking',
            name='expiration_time',
            field=models.DurationField(default=datetime.timedelta(seconds=240)),
        ),
    ]
