# Generated by Django 4.2.3 on 2023-07-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_matchmaking_created_at_matchmaking_expiration_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmaking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='matchmaking',
            name='expiration_time',
        ),
    ]
