# Generated by Django 4.2.3 on 2023-07-17 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_remove_matchmaking_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmaking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
