# Generated by Django 4.2.3 on 2023-07-20 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0005_remove_matchmaking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmaking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
