# Generated by Django 4.2.3 on 2023-07-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0006_matchmaking_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmaking',
            name='created_at',
        ),
    ]
